# Generated by Django 4.1.1 on 2022-09-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
